theme = "dracula"

[editor]
line-number = "relative"
# mouse = false
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-x = ":q" # Maps Ctrl-x to the typable command :q which is an alias for :quit (quit file)

[keys.insert]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-x = ":q" # Maps Ctrl-x to the typable command :q which is an alias for :quit (quit file)
