# bw
set -l bw_commands login logout lock unlock sync generate encode config update completion status list get create edit delete restore move confirm import export share send receive help
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a login -d "Log into a user account."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a logout -d "Log out of the current user account."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a lock -d "Lock the vault and destroy active session keys."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a unlock -d "Unlock the vault and return a new session key."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a sync -d "Pull the latest vault data from server."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a generate -d "Generate a password/passphrase."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a encode -d "Base 64 encode stdin."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a config -d "Configure CLI settings."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a update -d "Check for updates."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a completion -d "Generate shell completions."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a status -d "Show server, last sync, user information, and vault status."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a list -d "List an array of objects from the vault."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a get -d "Get an object from the vault."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a create -d "Create an object in the vault."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a edit -d "Edit an object from the vault."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a delete -d "Delete an object from the vault."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a restore -d "Restores an object from the trash."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a move -d "Move an item to an organization."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a confirm -d "Confirm an object to the organization."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a import -d "Import vault data from a file."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a export -d "Export vault data to a CSV or JSON file."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a share -d "--DEPRECATED-- Move an item to an organization."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a send -d "Work with Bitwarden Sends. A Send can be quickly created using this command or subcommands can be used to fine-tune the Send."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a receive -d "Access a Bitwarden Send from a url."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -a help -d "Display help for command."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -l pretty -d "Format output. JSON is tabbed with two spaces."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -l raw -d "Return raw output instead of a descriptive message."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -l response -d "Return a JSON formatted version of response output."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -l cleanexit -d "Exit with a success exit code (0) unless an error is thrown."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -l quiet -d "Do not return anything to stdout."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -l nointeraction -d "Do not prompt for interactive user input."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -l session -d "Pass session key instead of reading from env."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -l version -s v -d "Output the version number."
complete -f -c bw -n "not __fish_seen_subcommand_from $bw_commands" -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from login" -x -l method -d "Two-step login method."
complete -f -c bw -n "__fish_seen_subcommand_from login" -x -l code -d "Two-step login code."
complete -f -c bw -n "__fish_seen_subcommand_from login" -x -l sso -d "Log in with Single-Sign On."
complete -f -c bw -n "__fish_seen_subcommand_from login" -x -l apikey -d "Log in with an Api Key."
complete -f -c bw -n "__fish_seen_subcommand_from login" -x -l passwordenv -d "Environment variable storing your password."
complete -f -c bw -n "__fish_seen_subcommand_from login" -x -l passwordfile -d "Path to a file containing your password as its first line."
complete -f -c bw -n "__fish_seen_subcommand_from login" -x -l check -d "Check login status."
complete -f -c bw -n "__fish_seen_subcommand_from login" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from logout" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from lock" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from unlock" -x -l check -d "Check lock status."
complete -f -c bw -n "__fish_seen_subcommand_from unlock" -x -l passwordenv -d "Environment variable storing your password."
complete -f -c bw -n "__fish_seen_subcommand_from unlock" -x -l passwordfile -d "Path to a file containing your password as its first line."
complete -f -c bw -n "__fish_seen_subcommand_from unlock" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from sync" -x -l force -s f -d "Force a full sync."
complete -f -c bw -n "__fish_seen_subcommand_from sync" -x -l last -d "Get the last sync date."
complete -f -c bw -n "__fish_seen_subcommand_from sync" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from generate" -x -l uppercase -s u -d "Include uppercase characters."
complete -f -c bw -n "__fish_seen_subcommand_from generate" -x -l lowercase -s l -d "Include lowercase characters."
complete -f -c bw -n "__fish_seen_subcommand_from generate" -x -l number -s n -d "Include numeric characters."
complete -f -c bw -n "__fish_seen_subcommand_from generate" -x -l special -s s -d "Include special characters."
complete -f -c bw -n "__fish_seen_subcommand_from generate" -x -l passphrase -s p -d "Generate a passphrase."
complete -f -c bw -n "__fish_seen_subcommand_from generate" -x -l length -d "Length of the password."
complete -f -c bw -n "__fish_seen_subcommand_from generate" -x -l words -d "Number of words."
complete -f -c bw -n "__fish_seen_subcommand_from generate" -x -l separator -d "Word separator."
complete -f -c bw -n "__fish_seen_subcommand_from generate" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from encode" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from config" -x -l web-vault -d "Provides a custom web vault URL that differs from the base URL."
complete -f -c bw -n "__fish_seen_subcommand_from config" -x -l api -d "Provides a custom API URL that differs from the base URL."
complete -f -c bw -n "__fish_seen_subcommand_from config" -x -l identity -d "Provides a custom identity URL that differs from the base URL."
complete -f -c bw -n "__fish_seen_subcommand_from config" -x -l icons -d "Provides a custom icons service URL that differs from the base URL."
complete -f -c bw -n "__fish_seen_subcommand_from config" -x -l notifications -d "Provides a custom notifications URL that differs from the base URL."
complete -f -c bw -n "__fish_seen_subcommand_from config" -x -l events -d "Provides a custom events URL that differs from the base URL."
complete -f -c bw -n "__fish_seen_subcommand_from config" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from update" -x -l raw -d "Return only the download URL for the update."
complete -f -c bw -n "__fish_seen_subcommand_from update" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from completion" -x -l shell -d "Shell to generate completions for."
complete -f -c bw -n "__fish_seen_subcommand_from completion" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from status" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from list" -x -l search -d "Perform a search on the listed objects."
complete -f -c bw -n "__fish_seen_subcommand_from list" -x -l url -d "Filter items of type login with a url-match search."
complete -f -c bw -n "__fish_seen_subcommand_from list" -x -l folderid -d "Filter items by folder id."
complete -f -c bw -n "__fish_seen_subcommand_from list" -x -l collectionid -d "Filter items by collection id."
complete -f -c bw -n "__fish_seen_subcommand_from list" -x -l organizationid -d "Filter items or collections by organization id."
complete -f -c bw -n "__fish_seen_subcommand_from list" -x -l trash -d "Filter items that are deleted and in the trash."
complete -f -c bw -n "__fish_seen_subcommand_from list" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from get" -x -l itemid -d "Attachment's item id."
complete -f -c bw -n "__fish_seen_subcommand_from get" -x -l output -d "Output directory or filename for attachment."
complete -f -c bw -n "__fish_seen_subcommand_from get" -x -l organizationid -d "Organization id for an organization object."
complete -f -c bw -n "__fish_seen_subcommand_from get" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from create" -x -l file -d "Path to file for attachment."
complete -f -c bw -n "__fish_seen_subcommand_from create" -x -l itemid -d "Attachment's item id."
complete -f -c bw -n "__fish_seen_subcommand_from create" -x -l organizationid -d "Organization id for an organization object."
complete -f -c bw -n "__fish_seen_subcommand_from create" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from edit" -x -l organizationid -d "Organization id for an organization object."
complete -f -c bw -n "__fish_seen_subcommand_from edit" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from delete" -x -l itemid -d "Attachment's item id."
complete -f -c bw -n "__fish_seen_subcommand_from delete" -x -l organizationid -d "Organization id for an organization object."
complete -f -c bw -n "__fish_seen_subcommand_from delete" -x -l permanent -s p -d "Permanently deletes the item instead of soft-deleting it (item only)."
complete -f -c bw -n "__fish_seen_subcommand_from delete" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from restore" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from move" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from confirm" -x -l organizationid -d "Organization id for an organization object."
complete -f -c bw -n "__fish_seen_subcommand_from confirm" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from import" -x -l formats -d "List formats."
complete -f -c bw -n "__fish_seen_subcommand_from import" -x -l organizationid -d "ID of the organization to import to."
complete -f -c bw -n "__fish_seen_subcommand_from import" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from export" -x -l output -d "Output directory or filename."
complete -f -c bw -n "__fish_seen_subcommand_from export" -x -l format -d "Export file format."
complete -f -c bw -n "__fish_seen_subcommand_from export" -x -l organizationid -d "Organization id for an organization."
complete -f -c bw -n "__fish_seen_subcommand_from export" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from share" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from send" -x -l file -s f -d "Specifies that <data> is a filepath."
complete -f -c bw -n "__fish_seen_subcommand_from send" -x -l deleteInDays -s d -d "The number of days in the future to set deletion date, defaults to 7 (default: "7")."
complete -f -c bw -n "__fish_seen_subcommand_from send" -x -l maxAccessCount -s a -d "The amount of max possible accesses."
complete -f -c bw -n "__fish_seen_subcommand_from send" -x -l hidden -d "Hide <data> in web by default. Valid only if --file is not set."
complete -f -c bw -n "__fish_seen_subcommand_from send" -x -l name -s n -d "The name of the Send. Defaults to a guid for text Sends and the filename for files."
complete -f -c bw -n "__fish_seen_subcommand_from send" -x -l notes -d "Notes to add to the Send."
complete -f -c bw -n "__fish_seen_subcommand_from send" -x -l fullObject -d "Specifies that the full Send object should be returned rather than just the access url."
complete -f -c bw -n "__fish_seen_subcommand_from send" -x -l help -s h -d "Display help for command."
complete -f -c bw -n "__fish_seen_subcommand_from receive" -x -l password -d "Password needed to access the Send."
complete -f -c bw -n "__fish_seen_subcommand_from receive" -x -l passwordenv -d "Environment variable storing the Send's password."
complete -f -c bw -n "__fish_seen_subcommand_from receive" -x -l passwordfile -d "Path to a file containing the Sends password as its first line."
complete -f -c bw -n "__fish_seen_subcommand_from receive" -x -l obj -d "Return the Send's json object rather than the Send's content."
complete -f -c bw -n "__fish_seen_subcommand_from receive" -x -l output -d "Specify a file path to save a File-type Send to."
complete -f -c bw -n "__fish_seen_subcommand_from receive" -x -l help -s h -d "Display help for command."
